### ISSUE TITLE
Some tri planar projection are flipped 

### ISSUE THREAD

**Issue by unagi2152** [LoganFairbairn/matlayer#120]

**Comment by unagi2152** [comment]
![image](https://github.com/LoganFairbairn/matlayer/assets/86873681/3dadc5fe-23e5-44d6-9fb0-c3c2e096f7d4)

https://youtu.be/tsE7Tqlv8DQ?si=uSmFPASYwHoLU1fe You can follow this video for fix.

**Comment by LoganFairbairn** [comment]
It's been a while since I've looked at the triplanar setup regarding that math, but I may have left this un-flipped on purpose as it resulted in slightly less shader instructions.

I'll leave this ticket open until I look into this a bit more, and either implement a fix for this, or a toggle to swap between a performant shader without the flip and the one with the corrected flip.

**Comment by LoganFairbairn** [comment]
> ![image](https://user-images.githubusercontent.com/86873681/266792482-3dadc5fe-23e5-44d6-9fb0-c3c2e096f7d4.png)
> 
> https://youtu.be/tsE7Tqlv8DQ?si=uSmFPASYwHoLU1fe You can follow this video for fix.

Hi again, I've implemented a fix for this available on the main branch now. It is a bit of extra math for the shader, but doesn't seem to matter too much so I've opted to not have a toggle for this axis correction and instead it's just the default.

Take a look and let me know if this works,

Cheers!

**Comment by LoganFairbairn** [comment]
Seems I spoke too soon, the triplanar projection axis flip I implemented worked on my test sphere, but causes seems to appear where the axis is flipped. I'll have to re-disable this feature for now, and re-visit this in the future. 

I've pushed my attempted fix for this to the main branch though, you can view in in blend/Assets.blend

**Comment by LoganFairbairn** [comment]
Just needed to transform the normal from world to object space, seems to work now!
