### ISSUE TITLE
Plugin not allowed to be installed in script directories

### ISSUE THREAD

**Issue by chenpaner** [LoganFairbairn/matlayer#121]
If the plugin is installed in script directories, it will not be able to create new materials and will report an error. If it is installed in the default plugin folder, it will be no problem. Although this is not a big problem, I still have to tell you.

**Comment by chenpaner** [comment]
![Snipaste_2023-10-15_22-00-39](https://github.com/LoganFairbairn/matlayer/assets/107256886/ec4f8796-6fc8-4625-aef1-13fa90d2541a)
This offset don`t link

**Comment by LoganFairbairn** [comment]
> ![Snipaste_2023-10-15_22-00-39](https://user-images.githubusercontent.com/107256886/275330646-ec4f8796-6fc8-4625-aef1-13fa90d2541a.png) This offset don`t link

Hi there, I've re-written most of the internal code of the add-on within the last few months. MatLayer 2 (currently available on the main branch for testing) is much faster, more stable and includes the fix for this offset not linking. I strongly recommend using the version available on the main branch, or waiting until MatLayer 2 is officially released.

Happy Blending!

**Comment by LoganFairbairn** [comment]
> If the plugin is installed in script directories, it will not be able to create new materials and will report an error. If it is installed in the default plugin folder, it will be no problem. Although this is not a big problem, I still have to tell you.

Just to wrap this up...

The plugin is not intended to be installed in script directories, and must be installed as an add-on.

Although the tutorial is a bit outdated, the installation process for the add-on in [this tutorial](https://www.youtube.com/watch?v=o-fT5MXs5ds&t=967s) is not, so you can refer to it on how to properly install the add-on.

Happy Blending!
